name: SAP Cloud Integration deploy IFlow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: mavenBuild
        uses: SAP/project-piper-action@master
        with:
          command: mavenBuild
      - name: integrationArtifactDeploy
        uses: SAP/project-piper-action@master
        with:
          command: integrationArtifactDeploy
          flags: '--cpiApiServiceKeyCredentialsId ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId healthCheck'